- name: conditions
  hosts: local
  connection: local
  vars:
    number: 50
  tasks:
    - name: check the number is less than 50 or not
      ansible.builtin.debug:
        msg: "Given number is: {{ number }} is less than 100"
      when: number < 100