- name: conditions
  hosts: local
  connection: local
  vars:
    number: 50
  tasks:
    - name: check the number is less than 20 or not
      ansible.builtin.debug:
        msg: "Given number is: {{ number }} is less than 20"
      when: number < 25